In [1]:
import json
import pandas as pd
from pathlib import Path

In [2]:
project_root = Path.cwd().parent.parent
input_file = project_root / "data" / "raw" / "api" / "github" / "issues_response.json"

input_file

PosixPath('/Users/reda.serhir/Documents/Projects/Github/python-data-toolbox/data/raw/api/github/issues_response.json')

In [3]:
with open(input_file, "r") as file:
    issues_data = json.load(file)

type(issues_data), len(issues_data)

(list, 30)

In [4]:
issues_data[0]

{'url': 'https://api.github.com/repos/microsoft/vscode/issues/308230',
 'repository_url': 'https://api.github.com/repos/microsoft/vscode',
 'labels_url': 'https://api.github.com/repos/microsoft/vscode/issues/308230/labels{/name}',
 'comments_url': 'https://api.github.com/repos/microsoft/vscode/issues/308230/comments',
 'events_url': 'https://api.github.com/repos/microsoft/vscode/issues/308230/events',
 'html_url': 'https://github.com/microsoft/vscode/issues/308230',
 'id': 4218684145,
 'node_id': 'I_kwDOAn8RLM77dALx',
 'number': 308230,
 'title': 'WAY too many requests to allow something obvious',
 'user': {'login': 'MarcSchluperAtIntel',
  'id': 108437267,
  'node_id': 'U_kgDOBnafEw',
  'avatar_url': 'https://avatars.githubusercontent.com/u/108437267?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/MarcSchluperAtIntel',
  'html_url': 'https://github.com/MarcSchluperAtIntel',
  'followers_url': 'https://api.github.com/users/MarcSchluperAtIntel/followers',
  'following_url': 'https://api.github.com/users/MarcSchluperAtIntel/following{/other_user}',
  'gists_url': 'https://api.github.com/users/MarcSchluperAtIntel/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/MarcSchluperAtIntel/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/MarcSchluperAtIntel/subscriptions',
  'organizations_url': 'https://api.github.com/users/MarcSchluperAtIntel/orgs',
  'repos_url': 'https://api.github.com/users/MarcSchluperAtIntel/repos',
  'events_url': 'https://api.github.com/users/MarcSchluperAtIntel/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/MarcSchluperAtIntel/received_events',
  'type': 'User',
  'user_view_type': 'public',
  'site_admin': False},
 'labels': [],
 'state': 'open',
 'locked': False,
 'assignees': [],
 'milestone': None,
 'comments': 0,
 'created_at': '2026-04-07T15:15:37Z',
 'updated_at': '2026-04-07T15:15:37Z',
 'closed_at': None,
 'assignee': None,
 'author_association': 'NONE',
 'type': None,
 'active_lock_reason': None,
 'sub_issues_summary': {'total': 0, 'completed': 0, 'percent_completed': 0},
 'issue_dependencies_summary': {'blocked_by': 0,
  'total_blocked_by': 0,
  'blocking': 0,
  'total_blocking': 0},
 'body': '\nType: <b>Bug</b>\n\nI long for the day that Github Copilot in VS Code finally stops asking me to allow the most obvious things. Read my project folder?! Well, OF COURSE you need to read it.\nWrite in the project folder? Well, how else are you going to generate code? Generate it in memory only?!\n\nOccasionally it now enables me to change settings (automaticallY) that prevents these completely unwarranted holdups but in most cases it just stalls.\n\nThere is no going on a break and coming back seeing the work is finished. There is just: OMG, it stopped to ask me whether it can grep. Sigh.\n\nVS Code version: Code 1.114.0 (e7fb5e96c0730b9deb70b33781f98e2f35975036, 2026-04-01T09:27:11Z)\nOS version: Windows_NT x64 10.0.26100\nModes:\n\n<details>\n<summary>System Info</summary>\n\n|Item|Value|\n|---|---|\n|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|\n|GPU Status|2d_canvas: enabled<br>GPU0: VENDOR= 0x8086, DEVICE=0x9a49 [Intel(R) Iris(R) Xe Graphics], DRIVER_VENDOR=Intel, DRIVER_VERSION=32.0.101.7084 *ACTIVE*<br>GPU1: VENDOR= 0x1414, DEVICE=0x008c [Microsoft Basic Render Driver], DRIVER_VERSION=10.0.26100.7309<br>Machine model name: <br>Machine model version: <br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>trees_in_viz: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|\n|Load (avg)|undefined|\n|Memory (System)|63.72GB (39.06GB free)|\n|Process Argv|--crash-reporter-id 33f5345c-5727-48ae-af89-916737338b19|\n|Screen Reader|no|\n|VM|0%|\n</details><details><summary>Extensions (14)</summary>\n\nExtension|Author (truncated)|Version\n---|---|---\ncopilot-chat|Git|0.42.3\nvscode-peacock|joh|4.2.2\nmarp-vscode|mar|3.4.1\nprettify-json|moh|0.0.3\ncsdevkit|ms-|3.10.14\ncsharp|ms-|2.130.5\nvscode-dotnet-runtime|ms-|3.0.0\ndebugpy|ms-|2025.18.0\npython|ms-|2026.4.0\nvscode-python-envs|ms-|1.26.0\nremote-ssh|ms-|0.122.0\nremote-ssh-edit|ms-|0.87.0\nremote-explorer|ms-|0.5.0\nvscode-print|pdc|1.6.0\n\n\n</details><details>\n<summary>A/B Experiments</summary>\n\n```\nvsliv368:30146709\npythonvspyt551:31249599\nbinariesv615:30325510\nnativeloc1:31344060\ndwcopilot:31170013\ndwoutputs:31242946\ncopilot_t_ci:31333650\ne5gg6876:31282496\npythonrdcb7:31342333\n6518g693:31463988\naj953862:31281341\n4f60g487:31327383\n6abeh943:31336334\nenvsactivate1:31464700\ncloudbuttont:31379625\n3efgi100_wstrepl:31403338\n55ia6109:31457054\nuse-responses-api:31390855\ndefaultusage:31403421\nje187915:31401257\nec5jj548:31422691\nxtab-294-editdist-rl-2-med:31482038\ncp_cls_t_966_ss:31454198\na9239246:31485761\n4je02754:31466945\nc3h7c220:31478652\nge8j1254_inline_auto_hint_haiku:31431912\n38bie571_auto:31478677\ncp_cls_c_1081:31454833\nconptydll_false:31489735\nia-use-proxy-models-svc:31452481\ne9c30283:31461165\ntest_control1:31471004\nidci7584:31464702\nnes-ftch-ctrl:31485414\n3bj34942:31489864\ni54ji102:31458073\n534a6447:31478749\nnes-extended-on:31455476\nchat:31457767\n8hig5102:31480529\n67jbj424:31486320\nt-some:31486549\ncpptoolson-v2:31475363\ngithubstableflight:31469463\nregularsignin:31487065\nec1eg703:31488002\npo_split_t:31488386\nddid_c:31478207\ngetcmakediagnosticsoff:31489825\nja75b849:31489811\njah3f675:31485061\nnes-perm-reb-1:31490410\n\n```\n\n</details>\n\n<!-- generated by issue reporter -->',
 'closed_by': None,
 'reactions': {'url': 'https://api.github.com/repos/microsoft/vscode/issues/308230/reactions',
  'total_count': 0,
  '+1': 0,
  '-1': 0,
  'laugh': 0,
  'hooray': 0,
  'confused': 0,
  'heart': 0,
  'rocket': 0,
  'eyes': 0},
 'timeline_url': 'https://api.github.com/repos/microsoft/vscode/issues/308230/timeline',
 'performed_via_github_app': None,
 'state_reason': None,
 'pinned_comment': None}

In [5]:
normalized_issues = []

for issue in issues_data:
    issue_record = {
        "issue_id": issue["id"],
        "issue_number": issue["number"],
        "title": issue["title"],
        "state": issue["state"],
        "created_at": issue["created_at"],
        "updated_at": issue["updated_at"],
        "user_login": issue["user"]["login"],
        "comments": issue["comments"]
    }
    normalized_issues.append(issue_record)

normalized_issues[:2]

[{'issue_id': 4218684145,
  'issue_number': 308230,
  'title': 'WAY too many requests to allow something obvious',
  'state': 'open',
  'created_at': '2026-04-07T15:15:37Z',
  'updated_at': '2026-04-07T15:15:37Z',
  'user_login': 'MarcSchluperAtIntel',
  'comments': 0},
 {'issue_id': 4218680755,
  'issue_number': 308229,
  'title': 'Window keeps freezing',
  'state': 'open',
  'created_at': '2026-04-07T15:15:03Z',
  'updated_at': '2026-04-07T15:15:03Z',
  'user_login': 'jhaase1',
  'comments': 0}]

In [6]:
issues_df = pd.DataFrame(normalized_issues)
issues_df.head()

,issue_id,issue_number,title,state,created_at,updated_at,user_login,comments
0,4218684145,308230,WAY too many requests to allow something obvious,open,2026-04-07T15:15:37Z,2026-04-07T15:15:37Z,MarcSchluperAtIntel,0
1,4218680755,308229,Window keeps freezing,open,2026-04-07T15:15:03Z,2026-04-07T15:15:03Z,jhaase1,0
2,4218674628,308228,missing package-lock changes,open,2026-04-07T15:13:57Z,2026-04-07T15:17:14Z,joaomoreno,1
3,4218617116,308227,?,open,2026-04-07T15:04:31Z,2026-04-07T15:04:31Z,AmrGharibx,0
4,4218579314,308226,"i have a problem with my chat on code space, i...",open,2026-04-07T14:58:01Z,2026-04-07T14:58:34Z,briceT2f,1

In [7]:
issues_df.shape

(30, 8)

In [8]:
issues_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   issue_id      30 non-null     int64
 1   issue_number  30 non-null     int64
 2   title         30 non-null     str
 3   state         30 non-null     str
 4   created_at    30 non-null     str
 5   updated_at    30 non-null     str
 6   user_login    30 non-null     str
 7   comments      30 non-null     int64
dtypes: int64(3), str(5)
memory usage: 2.0 KB

In [9]:
issues_df["created_at"] = pd.to_datetime(issues_df["created_at"])
issues_df["updated_at"] = pd.to_datetime(issues_df["updated_at"])

issues_df.dtypes

issue_id                      int64
issue_number                  int64
title                           str
state                           str
created_at      datetime64[us, UTC]
updated_at      datetime64[us, UTC]
user_login                      str
comments                      int64
dtype: object

In [10]:
issues_df.sort_values(by="comments", ascending=False).head(10)

,issue_id,issue_number,title,state,created_at,updated_at,user_login,comments
15,4217955027,308211,add logging,open,2026-04-07 13:22:43+00:00,2026-04-07 13:25:48+00:00,sandy081,1
17,4217840212,308207,update.titleBar setting no longer recognized a...,open,2026-04-07 13:02:30+00:00,2026-04-07 13:42:49+00:00,Kvan7,1
2,4218674628,308228,missing package-lock changes,open,2026-04-07 15:13:57+00:00,2026-04-07 15:17:14+00:00,joaomoreno,1
4,4218579314,308226,"i have a problem with my chat on code space, i...",open,2026-04-07 14:58:01+00:00,2026-04-07 14:58:34+00:00,briceT2f,1
25,4217606586,308199,GitHub Copilot Broken this Morning,open,2026-04-07 12:21:54+00:00,2026-04-07 12:48:29+00:00,qwtm,1
8,4218195351,308219,hanging on fetching PDF url that saved to down...,open,2026-04-07 14:01:32+00:00,2026-04-07 14:45:45+00:00,ryanrocket,1
24,4217634758,308200,Chat is unresponsive,open,2026-04-07 12:27:18+00:00,2026-04-07 12:40:39+00:00,GloryFlory,1
28,4217418517,308194,Broken serialization,open,2026-04-07 11:44:54+00:00,2026-04-07 12:40:51+00:00,rohodragon,0
27,4217508641,308196,sunm,open,2026-04-07 12:02:17+00:00,2026-04-07 12:40:48+00:00,eriperdana598-netizen,0
26,4217568796,308198,Feature Request: Add a setting to configure th...,open,2026-04-07 12:14:24+00:00,2026-04-07 12:45:12+00:00,markusfalk,0

In [11]:
output_file = project_root / "data" / "cleaned" / "github_issue_records.csv"
issues_df.to_csv(output_file, index=False)

print(f"File saved: {output_file}")

File saved: /Users/reda.serhir/Documents/Projects/Github/python-data-toolbox/data/cleaned/github_issue_records.csv