In [1]:
import pandas as pd
from pathlib import Path

In [2]:
project_root = Path.cwd().parent.parent
input_file = project_root / "data" / "cleaned" / "retail" / "online_retail_clean.csv"

df = pd.read_csv(input_file)
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34

In [3]:
df.shape

(397884, 9)

In [4]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country', 'Revenue'],
      dtype='str')

In [5]:
high_revenue_df = df[df["Revenue"] > 1000]
high_revenue_df.shape

(315, 9)

In [6]:
high_revenue_df[["InvoiceNo", "StockCode", "Description", "Quantity", "UnitPrice", "Revenue"]].head(10)

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,Revenue
860,536477,21137,BLACK RECORD COVER FRAME,480,3.39,1627.20
1797,536584,84029E,RED WOOLLY HOTTIE WHITE HEART.,384,2.95,1132.80
3277,536785,22423,REGENCY CAKESTAND 3 TIER,144,10.95,1576.80
3606,536809,84950,ASSORTED COLOUR T-LIGHT HOLDER,1824,0.55,1003.20
3671,536830,21915,RED HARMONICA IN BOX,1400,1.06,1484.00
4436,536970,22423,REGENCY CAKESTAND 3 TIER,120,10.95,1314.00
7810,537235,22622,BOX OF VINTAGE ALPHABET BLOCKS,156,8.50,1326.00
8021,537256,21137,BLACK RECORD COVER FRAME,480,3.39,1627.20
9734,537456,22470,HEART OF WICKER LARGE,378,3.21,1213.38
10783,537657,82484,WOOD BLACK BOARD ANT WHITE FINISH,408,4.78,1950.24

In [7]:
uk_df = df[df["Country"] == "United Kingdom"]
uk_df.shape

(354321, 9)

In [8]:
non_uk_df = df[df["Country"] != "United Kingdom"]
non_uk_df.shape

(43563, 9)

In [9]:
sorted_by_revenue_df = df.sort_values(by="Revenue", ascending=False)
sorted_by_revenue_df[["InvoiceNo", "Description", "Country", "Revenue"]].head(10)

,InvoiceNo,Description,Country,Revenue
397411,581483,"PAPER CRAFT , LITTLE BIRDIE",United Kingdom,168469.60
37120,541431,MEDIUM CERAMIC TOP STORAGE JAR,United Kingdom,77183.60
155405,556444,PICNIC BASKET WICKER 60 PIECES,United Kingdom,38970.00
118341,551697,POSTAGE,United Kingdom,8142.75
248685,567423,SET OF TEA COFFEE SUGAR TINS PANTRY,United Kingdom,7144.72
109613,550461,FAIRY CAKE FLANNEL ASSORTED COLOUR,United Kingdom,6539.40
32727,540815,FAIRY CAKE FLANNEL ASSORTED COLOUR,United Kingdom,6539.40
308071,573003,RABBIT NIGHT LIGHT,Netherlands,4992.00
32725,540815,WHITE HANGING HEART T-LIGHT HOLDER,United Kingdom,4921.50
109609,550461,WHITE HANGING HEART T-LIGHT HOLDER,United Kingdom,4632.00

In [10]:
sorted_by_quantity_df = df.sort_values(by="Quantity", ascending=False)
sorted_by_quantity_df[["InvoiceNo", "Description", "Country", "Quantity"]].head(10)

,InvoiceNo,Description,Country,Quantity
397411,581483,"PAPER CRAFT , LITTLE BIRDIE",United Kingdom,80995
37120,541431,MEDIUM CERAMIC TOP STORAGE JAR,United Kingdom,74215
308102,573008,WORLD WAR 2 GLIDERS ASSTD DESIGNS,United Kingdom,4800
143230,554868,SMALL POPCORN HOLDER,United Kingdom,4300
61579,544612,EMPIRE DESIGN ROSETTE,United Kingdom,3906
188799,560599,ESSENTIAL BALM 3.5g TIN IN ENVELOPE,United Kingdom,3186
32727,540815,FAIRY CAKE FLANNEL ASSORTED COLOUR,United Kingdom,3114
109613,550461,FAIRY CAKE FLANNEL ASSORTED COLOUR,United Kingdom,3114
318078,573995,SMALL CHINESE STYLE SCISSOR,United Kingdom,3000
204025,562439,ASSORTED COLOUR BIRD ORNAMENT,United Kingdom,2880

In [11]:
selected_columns_df = df[[
    "InvoiceNo",
    "InvoiceDate",
    "CustomerID",
    "Country",
    "Quantity",
    "UnitPrice",
    "Revenue"
]]

selected_columns_df.head()

,InvoiceNo,InvoiceDate,CustomerID,Country,Quantity,UnitPrice,Revenue
0,536365,2010-12-01 08:26:00,17850,United Kingdom,6,2.55,15.30
1,536365,2010-12-01 08:26:00,17850,United Kingdom,6,3.39,20.34
2,536365,2010-12-01 08:26:00,17850,United Kingdom,8,2.75,22.00
3,536365,2010-12-01 08:26:00,17850,United Kingdom,6,3.39,20.34
4,536365,2010-12-01 08:26:00,17850,United Kingdom,6,3.39,20.34

In [12]:
selected_columns_df.describe()

,InvoiceNo,CustomerID,Quantity,UnitPrice,Revenue
count,397884.000000,397884.000000,397884.000000,397884.000000,397884.000000
mean,560616.934451,15294.423453,12.988238,3.116488,22.397000
std,13106.117773,1713.141560,179.331775,22.097877,309.071041
min,536365.000000,12346.000000,1.000000,0.001000,0.001000
25%,549234.000000,13969.000000,2.000000,1.250000,4.680000
50%,561893.000000,15159.000000,6.000000,1.950000,11.800000
75%,572090.000000,16795.000000,12.000000,3.750000,19.800000
max,581587.000000,18287.000000,80995.000000,8142.750000,168469.600000