In [1]:
import pandas as pd
from pathlib import Path

In [2]:
project_root = Path.cwd().parent.parent
input_file = project_root / "data" / "cleaned" / "retail" / "online_retail_clean.csv"

df = pd.read_csv(input_file)
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34

In [3]:
df.shape

(397884, 9)

In [4]:
country_revenue_df = (
    df.groupby("Country", as_index=False)["Revenue"]
    .sum()
    .sort_values(by="Revenue", ascending=False)
)

country_revenue_df.head(10)

           Country      Revenue
35  United Kingdom  7308391.554
23     Netherlands   285446.340
10            EIRE   265545.900
14         Germany   228867.140
13          France   209024.050
0        Australia   138521.310
30           Spain    61577.110
32     Switzerland    56443.950
3          Belgium    41196.340
31          Sweden    38378.330

In [5]:
customer_revenue_df = (
    df.groupby("CustomerID", as_index=False)["Revenue"]
    .sum()
    .sort_values(by="Revenue", ascending=False)
)

customer_revenue_df.head(10)

      CustomerID    Revenue
1689       14646  280206.02
4201       18102  259657.30
3728       17450  194550.79
3008       16446  168472.50
1879       14911  143825.06
55         12415  124914.53
1333       14156  117379.63
3771       17511   91062.38
2702       16029   81024.84
0          12346   77183.60

In [6]:
product_revenue_df = (
    df.groupby(["StockCode", "Description"], as_index=False)["Revenue"]
    .sum()
    .sort_values(by="Revenue", ascending=False)
)

product_revenue_df.head(10)

     StockCode                         Description    Revenue
2602     23843         PAPER CRAFT , LITTLE BIRDIE  168469.60
1318     22423            REGENCY CAKESTAND 3 TIER  142592.95
3459    85123A  WHITE HANGING HEART T-LIGHT HOLDER  100448.15
3444    85099B             JUMBO BAG RED RETROSPOT   85220.78
2100     23166      MEDIUM CERAMIC TOP STORAGE JAR   81416.73
3896      POST                             POSTAGE   77803.96
2799     47566                       PARTY BUNTING   68844.33
3278     84879       ASSORTED COLOUR BIRD ORNAMENT   56580.34
3894         M                              Manual   53779.93
2006     23084                  RABBIT NIGHT LIGHT   51346.20

In [7]:
country_quantity_df = (
    df.groupby("Country", as_index=False)["Quantity"]
    .sum()
    .sort_values(by="Quantity", ascending=False)
)

country_quantity_df.head(10)

           Country  Quantity
35  United Kingdom   4256740
23     Netherlands    200361
10            EIRE    140275
14         Germany    119261
13          France    111471
0        Australia     83901
31          Sweden     36083
32     Switzerland     30082
30           Spain     27940
19           Japan     26016

In [8]:
invoice_revenue_df = (
    df.groupby("InvoiceNo", as_index=False)["Revenue"]
    .sum()
    .sort_values(by="Revenue", ascending=False)
)

invoice_revenue_df.head(10)

       InvoiceNo    Revenue
18499     581483  168469.60
1909      541431   77183.60
7925      556444   38970.00
12417     567423   31698.16
8111      556917   22775.93
14456     572209   22206.00
12409     567381   22104.80
10842     563614   21880.44
5462      550461   21535.90
14368     572035   20277.92

In [9]:
country_summary_df = (
    df.groupby("Country", as_index=False)
    .agg(
        total_revenue=("Revenue", "sum"),
        total_quantity=("Quantity", "sum"),
        average_unit_price=("UnitPrice", "mean")
    )
    .sort_values(by="total_revenue", ascending=False)
)

country_summary_df.head(10)

           Country  total_revenue  total_quantity  average_unit_price
35  United Kingdom    7308391.554         4256740            2.963994
23     Netherlands     285446.340          200361            2.648465
10            EIRE     265545.900          140275            4.447109
14         Germany     228867.140          119261            3.709308
13          France     209024.050          111471            4.415782
0        Australia     138521.310           83901            3.056261
30           Spain      61577.110           27940            3.826224
32     Switzerland      56443.950           30082            3.470543
3          Belgium      41196.340           23237            3.630158
31          Sweden      38378.330           36083            3.760067

In [10]:
country_summary_df.describe()

       total_revenue  total_quantity  average_unit_price
count   3.700000e+01    3.700000e+01           37.000000
mean    2.408489e+05    1.396706e+05            5.459493
std     1.196639e+06    6.971546e+05            8.994877
min     1.459200e+02    8.000000e+01            2.047383
25%     2.667070e+03    9.820000e+02            3.146184
50%     1.359038e+04    5.241000e+03            4.173364
75%     3.837833e+04    2.601600e+04            4.717955
max     7.308392e+06    4.256740e+06           58.333288