In [1]:
import pandas as pd
from pathlib import Path

In [2]:
project_root = Path.cwd().parent.parent
input_file = project_root / "data" / "cleaned" / "retail" / "online_retail_clean.csv"

df = pd.read_csv(input_file)
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34

In [3]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])
df["InvoiceMonth"] = df["InvoiceDate"].dt.to_period("M").astype(str)

df[["InvoiceDate", "InvoiceMonth"]].head()

          InvoiceDate InvoiceMonth
0 2010-12-01 08:26:00      2010-12
1 2010-12-01 08:26:00      2010-12
2 2010-12-01 08:26:00      2010-12
3 2010-12-01 08:26:00      2010-12
4 2010-12-01 08:26:00      2010-12

In [4]:
monthly_revenue_df = (
    df.groupby("InvoiceMonth", as_index=False)["Revenue"]
    .sum()
    .sort_values(by="InvoiceMonth")
)

monthly_revenue_df.head(12)

   InvoiceMonth      Revenue
0       2010-12   572713.890
1       2011-01   569445.040
2       2011-02   447137.350
3       2011-03   595500.760
4       2011-04   469200.361
5       2011-05   678594.560
6       2011-06   661213.690
7       2011-07   600091.011
8       2011-08   645343.900
9       2011-09   952838.382
10      2011-10  1039318.790
11      2011-11  1161817.380

In [5]:
monthly_country_revenue_pivot = pd.pivot_table(
    df,
    values="Revenue",
    index="InvoiceMonth",
    columns="Country",
    aggfunc="sum",
    fill_value=0
)

monthly_country_revenue_pivot.head()

Country,Australia,Austria,Bahrain,Belgium,Brazil,Canada,Channel Islands,Cyprus,Czech Republic,Denmark,...,RSA,Saudi Arabia,Singapore,Spain,Sweden,Switzerland,USA,United Arab Emirates,United Kingdom,Unspecified
InvoiceMonth,,,,,,,,,,,,,,,,,,,,,
2010-12,1032.85,277.20,0.0,1809.91,0.0,0.00,363.53,1590.82,0.00,1281.50,...,0.0,0.00,0.00,1843.73,3834.30,1304.92,0.00,0.00,498661.850,0.0
2011-01,9017.71,0.00,0.0,1200.20,0.0,0.00,675.58,547.50,0.00,0.00,...,0.0,0.00,2053.07,10086.09,3486.32,4231.23,0.00,0.00,442190.060,0.0
2011-02,14695.42,518.36,0.0,2181.07,0.0,0.00,1784.71,4334.24,549.26,399.22,...,0.0,145.92,0.00,2114.50,509.50,2654.92,0.00,889.24,355655.630,0.0
2011-03,17223.99,1708.12,0.0,3351.98,0.0,140.54,3509.33,938.39,0.00,3978.99,...,0.0,0.00,0.00,5363.15,4720.58,1870.23,0.00,0.00,467198.590,0.0
2011-04,771.60,680.78,0.0,1989.48,1143.6,0.00,293.00,0.00,0.00,0.00,...,0.0,0.00,8209.58,1785.65,809.10,2076.94,383.95,0.00,409559.141,299.1

In [6]:
monthly_country_revenue_pivot.shape

(13, 37)

In [7]:
top_countries = (
    df.groupby("Country", as_index=False)["Revenue"]
    .sum()
    .sort_values(by="Revenue", ascending=False)
    .head(5)["Country"]
    .tolist()
)

top_countries

['United Kingdom', 'Netherlands', 'EIRE', 'Germany', 'France']

In [8]:
top_country_pivot = monthly_country_revenue_pivot[top_countries]
top_country_pivot.head()

Country       United Kingdom  Netherlands      EIRE   Germany    France
InvoiceMonth
2010-12           498661.850      8784.48   8813.88  15241.14   9616.31
2011-01           442190.060     26611.16  21904.19  16910.84  17740.12
2011-02           355655.630     23011.91  10126.52   9581.05   8515.96
2011-03           467198.590     22416.49  21674.36  14392.69  14589.55
2011-04           409559.141      2976.56   7570.50  12315.54   5529.61

In [9]:
top_country_pivot

Country       United Kingdom  Netherlands      EIRE   Germany    France
InvoiceMonth
2010-12           498661.850      8784.48   8813.88  15241.14   9616.31
2011-01           442190.060     26611.16  21904.19  16910.84  17740.12
2011-02           355655.630     23011.91  10126.52   9581.05   8515.96
2011-03           467198.590     22416.49  21674.36  14392.69  14589.55
2011-04           409559.141      2976.56   7570.50  12315.54   5529.61
2011-05           551568.820     29185.88  15982.19  25751.20  17614.88
2011-06           524915.480     26858.09  19835.99  13274.10  16078.97
2011-07           485612.251        26.02  40905.15  16440.98  10000.19
2011-08           498453.320     40327.81  16967.38  19220.77  13810.96
2011-09           796780.272     26937.26  40995.49  18091.22  23428.04
2011-10           824766.220     40708.65  24317.92  31638.42  33485.45
2011-11           980645.750     25874.01  29473.41  28025.02  31337.09
2011-12           472384.170     11728.02   6978.92   7984.17   7276.92

In [10]:
top_country_pivot.describe()

Country,United Kingdom,Netherlands,EIRE,Germany,France
count,13.000000,13.000000,13.000000,13.000000,13.000000
mean,562183.965692,21957.410769,20426.607692,17605.164615,16078.773077
std,185290.242641,12740.656232,11410.198974,7048.310590,8789.041581
min,355655.630000,26.020000,6978.920000,7984.170000,5529.610000
25%,467198.590000,11728.020000,10126.520000,13274.100000,9616.310000
50%,498453.320000,25874.010000,19835.990000,16440.980000,14589.550000
75%,551568.820000,26937.260000,24317.920000,19220.770000,17740.120000
max,980645.750000,40708.650000,40995.490000,31638.420000,33485.450000